### ISSUE TITLE
一連の流れを確認する

### ISSUE THREAD

**Issue by MATSUZAKIYuto** [naoido/web-programming#1]
自分のやることをIsuueを立てるのテスト
docker desktop Install;
ローカルでブランチを作成する
ローカルで変更を加えたのち、コミットし、プッシュする
Issueに関連させ、プルリクエストを作成する
私のコードレビュー後マージする

**Comment by naoido** [comment]
@MATSUZAKIYuto 
Issue立てるのはナイスだけど、タイトルはわかりやすく！！
今回の例だと「一連の流れを確認する」みたいな感じにして、Assignessに自分を割り当てるほうがいいかな〜〜
適当にIssue立てていくとごちゃるから、チーム開発ではここらへん気をつけて！！

**Comment by naoido** [comment]
一応今回だけこっちで変えといた

**Comment by MATSUZAKIYuto** [comment]
ありがとうございます！
